version: 2

updates:
  - package-ecosystem: "github-actions"
    target-branch: "dependabot-staging"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "(Action Update):"

  - package-ecosystem: "npm"
    target-branch: "dependabot-staging"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "(Dep Update):"
      prefix-development: "(Dev Dep Update):"
